name: Continuous integration
on: [push, pull_request]
env:
  nixpkgs-url: https://github.com/NixOS/nixpkgs/archive/574d1eac1c200690e27b8eb4e24887f8df7ac27c.tar.gz
jobs:
  build-pdf:
    name: Generate PDF artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=${{ env.nixpkgs-url }}
    - name: Build Nix dependencies
      run: nix-shell --pure --run "echo '=== Nix dependencies installed ==='"
    - name: Make Manuscript PDF
      run: nix-shell --pure --run "make tbagrel_phd_manuscript.pdf"
    - name: Make Presentation PDF
      run: nix-shell --pure --run "make tbagrel_phd_presentation.pdf"
    - name: Upload Manuscript PDF
      uses: actions/upload-artifact@v4
      with:
        name: tbagrel_phd_manuscript
        path: tbagrel_phd_manuscript.pdf
        retention-days: 90
    - name: Upload Presentation PDF
      uses: actions/upload-artifact@v4
      with:
        name: tbagrel_phd_presentation
        path: tbagrel_phd_presentation.pdf
        retention-days: 90
